# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Concepts
  items:
    - label: 'The Network State'
      link: '/concepts/network-state'
    - label: 'Bitcoin'
      link: '/concepts/bitcoin-flag'
    - label: 'The Citizen Journalist'
      link: '/concepts/citizen-journalism'
    - label: 'Tech evangelism'
      link: '/concepts/evangelize-tech'
    - label: 'Pseudoanonymous Economy'
      link: '/concepts/pseudoanonymous-economy'
    - label: 'The Purpose Of Technology'
      link: '/concepts/purpose-technology'
- label: Other
  items:
    - label: Sources
      link: '/sources'
